### PR TITLE
Remove deprecated autoprefixer and add tests

### PR DESCRIPTION
**Pull request by jameswomack**
* Remove deprecated autoprefixer-core
* Update PostCSS & Autoprefixer
* Add unit tests for 100% coverage and self-documentation

### CODE REVIEW

**Comment by Xuanwo** [comment]
Nice work, and I will contect tommy to  open the CI for this repo !

**Comment by jameswomack** [comment]
:+1:

**Comment by tommy351** [comment]
CI is available now.

https://travis-ci.org/hexojs/hexo-autoprefixer

**Comment by tommy351** [comment]
1.0.0 has been published! :tada:

**Comment by Xuanwo** [comment]
:tada:

**Comment by jameswomack** [comment]
:fireworks:

**Pull request merged**
